### ISSUE TITLE
Doesn't seem to be functional

### ISSUE THREAD

**Issue by Rionoskae** [stephenyeargin/angularjs-brewery-db#1]
Downloaded .zip copy of the repo, and when I open the index.html file it only pulls up the HTML formatting, but unable to pull in info from the BreweryDB api ( despite adding mine in )

Any chance on elaborating on the implementation?

**Comment by stephenyeargin** [comment]
I'm guessing you are on a web server with PHP enabled, and that you have

> Copy the `config.php-dist` file to `config.php` and insert your Brewery DB API Key.

Try going to `random.php` in your browser and see if it returns a JSON feed.

**Comment by Rionoskae** [comment]
I do in PHPfiddle.org - but not on my own site...

'{"message":"Request Successful","data":{"id":"yJyH88","name":"Heubacher Weizen","abv":"4.7","styleId":49,"isOrganic":"N","status":"verified","statusDisplay":"Verified","createDate":"2012-08-12 12:01:45","updateDate":"2012-08-18 15:35:15","style":{"id":49,"categoryId":4,"category":{"id":4,"name":"German Origin Ales","createDate":"2012-03-21 20:06:46"},"name":"South German-Style Kristall Weizen \/ Kristall Weissbier","description":"The aroma and flavor of a Weissbier without yeast is very similar to Weissbier with yeast (Hefeweizen\/Hefeweissbier) with the caveat that fruity and phenolic characters are not combined with the yeasty flavor and fuller-bodied mouthfeel of yeast. The phenolic characteristics are often described as clove- or nutmeg-like and can be smoky or even vanilla-like. Banana-like esters are often present. These beers are made with at least 50 percent malted wheat, and hop rates are quite low. Hop flavor and aroma are absent. Weissbier is well attenuated and very highly carbonated, yet its relatively high starting gravity and alcohol content make it a medium- to full-bodied beer. The color is very pale to deep golden. Because the beer has been filtered, yeast is not present. The beer will have no flavor of yeast and a cleaner, drier mouthfeel. The beer should be clear with no chill haze present. No diacetyl should be perceived.","ibuMin":"10","ibuMax":"15","abvMin":"4.9","abvMax":"5.5","srmMin":"3","srmMax":"9","ogMin":"1.047","fgMin":"1.008","fgMax":"1.016","createDate":"2012-03-21 20:06:46","updateDate":"2012-07-06 18:07:22"}},"status":"success"}    <div class="container" ng-controller="AppController as app" ng-show="'app.beer'">'

This is what I get when I move my phpfiddle.org code over to my site....
![random-beer](https://cloud.githubusercontent.com/assets/5183136/6134474/4eb253ce-b127-11e4-8d72-fac8017225a5.png)

**Comment by stephenyeargin** [comment]
You won't be able to work with the front end code until the JSON feed works. It sounds like your server may have trouble running PHP? Check the error logs to see what may be happening if you are getting a white screen.

**Comment by Rionoskae** [comment]
I've got the random.php to show the JSON feed now!  After several minutes of playing around with the files you provided I got it working! It would seem that most of my issues could be attiributed to index.html not being able to see the app.js file :) My Bad!

Thanks for all the help.

**Comment by stephenyeargin** [comment]
:+1:
